### PR TITLE
Feature/landing station control CU-23dq197

### PR DESCRIPTION
**Pull request by adschne**
This PR adds a landing station control interface. It can be shown/hidden by clicking on the LS status indicator in the top bar.

The interface contains buttons to move the glider up and town, turn it left anright, open and close the hook and trigger a delivery.
The interface also has two text fields to set the speed of the belts and the timeout (how long the belts move after a button is pressed) 
When a button is pressed, a NAMED_VALUE_FLOAT message with the right name and value is sent over mavlink. The mavlink-router on the glider then forwards the messages for the landing station to it if the glider is connected to the landing station wifi. The messages for the hook and the delivery are handled directly by the glider.

Screenshot of the interface:
image

Video of operation can be found in the [clickup ticket](https://app.clickup.com/t/23dq197)

P.S.
The first commit fixes an issue where the enum of orientations in SensorsSetup.qml is not the same as on PX4 which meant that the orientation selector did not work. With the updated list QGC and PX4 are  the same and the selected orientation in QGC results in the same orientation on the pixhawk

### CODE REVIEW

**Comment by julia-nitsch** [comment]
Task linked: [CU-23dq197 Make manual hooking operator friendly](https://app.clickup.com/t/23dq197)

**Review by julia-nitsch — COMMENTED** [review]
Hey @adschne,

thanks for adding it to QGC, LGTM :+1: However I think @RafikHachana should give the approval here :wink:. 

One more thing about the streamed image: Have we already found out if gstreamer uses bandwidth if the image is not received? Do we need to implement a logic on the auto-landing-detection repo thus that this image is only available in landing and starting preperation mode?

**Comment by adschne** [comment]
> Have we already found out if gstreamer uses bandwidth if the image is not received?

Hey @julia-nitsch,  this has not been checked yet, i created a [ticket](https://app.clickup.com/t/263bfv9) for it.

**Review by RafikHachana — APPROVED** [review]
Hey @adschne , LGTM! Thanks for the new feature, everything is perfectly in place.

I just have a couple of suggestions/comments:
- In line 65 of `src/QmlControls/LandingStationIndicator.qml`, we can assign a function to onClicked that checks whether or not we are connected to LS in the first place, so that we don't accidentally open the control menu mid-flight. (Just check the `landingStationConnected` property of the vehicle that is used in line 30 of the same file). I think it's definitely nice to have.

- (Definitely not for this PR!) I think it would be more practical to setup keyboard shortcuts for this to make it more usable (I guess that it was already in your plan if I remember correctly). We can also set up a joystick plugin for it.

**Comment by adschne** [comment]
Thanks @RafikHachana, those are some very good points. I updated the code to only show the control buttons when we are connected to a landing station.

**Review by RafikHachana — APPROVED** [review]

**Pull request merged**
