### PR TITLE
Feature/log transfer button CU-1xwmv2b

### PR DESCRIPTION
**Pull request by adschne**
This PR adds an addtional button to the log download page. 

The button acts exactly like the Download button when log files are selected, except that instead of downloading the log files to the local computer, it directly uploads them from the pixhawk to our sharepoint, in the folder corresponding to the current date and the IP adress of the glider it came from. If a file exists already, it is not uploaded and the user is notified.
If no log files are selected and the button is pressed, it first refreshes the list of available log files (we don't have to do anything here, this is done from the Jetson) and then checks for each file if it is on sharepoint already and if not uploads it.

A video of the button in action can be seeen in the comments of [this ticket](https://app.clickup.com/t/1xwmv2b)

Pros:
* transfering logs to sharepoint is very easy for operators, all they have to do is go to the log download page and click the sharepoint button
* If soemthing doesn't work (see cons), the process can be cancelled and the unsuccesull files can be selected and transferred seperately

Cons:
* The code of the sharepoint button is somewhat hijacking other functions usually used for the log dowload (e.g. to provide a rough estimate how much data has been transfered already without downloading the log ourselves). This is somewhat hacky
* The communication with ROS at the moment works through NAMED_VALUE_FLOAT messages and is not very reliable. Sometimes commands don't get executed and have to be resent. This should be fixed in the future with creating our own mavlink message for those topics.

This PR is related to the [corresponding PR](https://github.com/PackageGlider/auto-landing-detection/pull/78) in the auto-landing-detection repo, which adds the necessary functionality in ROS

### CODE REVIEW

**Comment by julia-nitsch** [comment]
Task linked: [CU-1xwmv2b Integration of logUploader for operator friendly usage](https://app.clickup.com/t/1xwmv2b)

**Review by julia-nitsch — COMMENTED** [review]
Hey @adschne I reviewed to ROS counterpart already but I need to leave this one for @RafikHachana.

**Review by RafikHachana — APPROVED** [review]
Hey @adschne , lgtm. For the 2 cons of the current approach we can add ClickUp tickets for them in the backlog.

Edit: Created tickets [here](https://app.clickup.com/t/26mrtuf) and [here](https://app.clickup.com/t/26mru1q) (For the far future ofc).

**Comment by adschne** [comment]
@RafikHachana, thanks for the tickets!

**Pull request merged**
